### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by travier** [comment]
https://discourse.flathub.org/t/freedesktop-sdk-22-08-0-released/2871/3

**Comment by travier** [comment]
We don't use this SDK yet

**Comment by yselkowitz** [comment]
> We don't use this SDK yet

Why not?

**Comment by travier** [comment]
As it's mentioned in the link above, it's still missing some setup, themes branches, etc. before it can be used by apps here.

**Comment by yselkowitz** [comment]
That's rather disappointing, given how long 22.08 has been out.

**Comment by travier** [comment]
@yselkowitz Please help us on this front then if you want to use it.

**Pull request closed without merging**
